---
title: "Normalizing Data"
author: "Connor Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, ggtext, png, jpeg, showtext)
theme_set(theme_minimal())
library(plotly)
library(highcharter)
```

Read in Alc_per_year data
```{r}
Alc_per_year = read_csv("Alc_per_year.csv")
Alc_per_person = read_csv("alc_per_person.csv")
```

```{r}
#| fig-width: 12
#| fig-height: 8
highchart() %>% 
hc_xAxis(categories = Alc_per_person$Year) %>% 
hc_add_series(name = "Total Alcohol w/o Inflation", data = Alc_per_person$`Total Alc`, type = "line") %>% 
hc_add_series(name = "Total Alcohol w/ Inflation", data = Alc_per_person$with_inflation, type = "line") %>%
hc_add_series(name = "Alcohol per Person w/o Inflation", data = Alc_per_person$`w/o_Inflation`, type = "line") %>% 
hc_add_series(name = "Alcohol per Person w/ Inflation", data = Alc_per_person$Total_Alc_per_person_inflation, type = "line") %>%
hc_tooltip(
  shared = TRUE,
  headerFormat = "<b>Year: {point.x}</b><br/>",
  formatter = JS("function() {
    var points = this.points;
    var order = {
      'Total Alcohol w/o Inflation': 1,
      'Total Alcohol w/ Inflation': 2,
      'Alcohol per Person w/o Inflation': 3,
      'Alcohol per Person w/ Inflation': 4
    };
    var labels = {
      'Total Alcohol w/o Inflation': 'Raw Data',
      'Total Alcohol w/ Inflation': 'Inflation',
      'Alcohol per Person w/o Inflation': 'Population',
      'Alcohol per Person w/ Inflation': 'Inflation and Population'
    };
    
    points.sort(function(a, b) {
      return order[a.series.name] - order[b.series.name];
    });
    
    var s = '<b>Year: ' + this.x + '</b><br/>';
    points.forEach(function(point) {
      var isPopulationSeries = point.series.name.includes('per Person');
      var suffix = isPopulationSeries ? '' : 'M';
      s += labels[point.series.name] + ': $' + Math.round(point.y) + suffix + '<br/>';
    });
    return s;
  }")
) %>%
hc_plotOptions(
  series = list(
    reverseStacks = TRUE
  )
) %>%
hc_legend(
  enabled = TRUE,
  reversed = FALSE,
  labelFormatter = JS("function() {
    var labels = {
      'Total Alcohol w/o Inflation': 'Raw Data',
      'Total Alcohol w/ Inflation': 'Inflation',
      'Alcohol per Person w/o Inflation': 'Population',
      'Alcohol per Person w/ Inflation': 'Inflation and Population'
    };
    return labels[this.name] || this.name;
  }")
) %>%
hc_yAxis(
  labels = list(
    formatter = JS("function() { return '$' + (this.value).toLocaleString(); }")
  ),
  title = list(text = "")
) %>%
hc_title(
  text = "Money Spent on Alcohol in San Antonio ðŸº",
  style = list(fontSize = "18px")
) %>%
hc_subtitle(
  text = "Comparing Inflation and Population Adjustments",
  style = list(fontSize = "14px")
) %>%
hc_add_theme(hc_theme_flat())
```

